### ISSUE TITLE
jscalendar: different types for daylight and standard properties

### ISSUE THREAD

**Issue by adriano-di-giovanni** [CalConnect/PUBLIC_DRAFTS#19]
In [8.2.6.  Initial Contents for the JSCalendar Properties Registry](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-32#section-8.2.6), `daylight` and `standard` properties are of type `TimeZoneRule`.

In [4.7.2.  timeZones](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-32#section-4.7.2), the same two properties are of type `TimeZoneRule[]`.

Which is correct?

**Comment by neilj** [comment]
Section 4.7.2 is correct; thanks!
