### ISSUE TITLE
jscalendar: partial @type enumeration + casing inconsistency

### ISSUE THREAD

**Issue by adriano-di-giovanni** [CalConnect/PUBLIC_DRAFTS#21]
In [4.1.1.  @type](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-32#section-4.1.1) is stated that the `@type` property  MUST be one of the following values:
* jsevent
* jstask
* jsgroup

What about the other values?
* Location
* VirtualLocation
* RecurrenceRule
* NDay
* Participant
* Alert
* OffsetTrigger
* AbsoluteTrigger
* TimeZone
* TimeZoneRule

In [8.2.6.  Initial Contents for the JSCalendar Properties Registry](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-32#section-8.2.6), the property context for `@types` extends to more object types than `JSEvent`, `JSTask`, `JSGroup`.

Is casing inconsistency between `jsevent`, `jstask`, `jsgroup` and the other values (e.s. `VirtualLocation`) an issue?

**Comment by adriano-di-giovanni** [comment]
@neilj , is it relevant?

**Comment by rsto** [comment]
@adriano-di-giovanni thanks, it is relevant, we just didn't come to a final conclusion how to deal with the case inconsistency.

The `@type` property definitions are correct, and we do no plan to update them: the `@type` definition in section 4.1.1 defines the allowed values for the top-level JSCalendar objects, and these only can be an event, a task or a group. Note that the definition of each other type (like Location), defines the allowed value for their `@type` property as well. Section 8.2.6 then defines all possible values of a `@type` property, without taking into account the restrictions of the respective object type.

The case inconsistency indeed is an issue that we'll need to fix. We will either use camel-case or lower-case, but prefer to keep case-sensitivity. I expect to update the draft this week.

**Comment by adriano-di-giovanni** [comment]
thank you very much for the great work

**Comment by rsto** [comment]
Fixed in https://github.com/CalConnect/PUBLIC_DRAFTS/commit/0431a2210e3dfc0ba610c0f4319cc2b2efe1ff5e
Thanks for the input @adriano-di-giovanni!
