### ISSUE TITLE
Add 'previous' relatedTo value or replace 'first' with 'previous'?

### ISSUE THREAD

**Issue by rsto** [CalConnect/PUBLIC_DRAFTS#4]
Currently, the spec says about this-and-future splits:

    A "relation=["next"]" relatedTo property SHOULD be set on the
    original object with the uid of the new object.  A
    "relation=["first"]" relatedTo property with the UID of the first
    object in the series SHOULD be set on the new object.  Clients can
    then follow these UIDs to get the complete set of objects if the user
    wishes to modify them all at once.

Probably the `first` should be replaced with `previous`? Need to talk to client developers what makes sense for them.

**Comment by dmfs** [comment]
`first` is probably easier, because it's an id shared by all instances in the series. This way you don't have to traverse a linked list to find all instances which are part of the series.

**Comment by evert** [comment]
If these are link relations, you might also consider `collection` or `original`, but frankly `first` sounds the best to me.

**Comment by neilj** [comment]
We discussed this before at length: first + next was chosen so you have a consistent id for every one in the set (the "first" uid) and can follow the chain to find all of them treating it is a linked list, and if you split a recurrence you only ever have to update the one you're splitting and create the new one.
